core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

taskly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("accounts.urls")),
    path('', include("core.urls")),
    path('tasks/', include("tasks.urls", namespace="tasks")),
    path('admin/', admin.site.urls),
]

tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createTask, name="createTask"),
    path("<int:task_id>/", views.singleTask, name="singleTask"),
    path("<int:task_id>/update/", views.updateTask, name="updateTask"),
    path("<int:task_id>/delete/", views.deleteTask, name="deleteTask"),
    path("<int:task_id>/complete/", views.completeTask, name="completeTask"),
    path("completed/", views.completedTasks, name="completedTasks"),
    path("scheduled/", views.scheduledTasks, name="scheduledTasks"),
    path("pending/", views.pendingTasks, name="pendingTasks"),
    path("running/", views.runningTasks, name="runningTasks"),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now_add=True)
    start_at = models.DateField()
    due_at = models.DateField()
    is_completed = models.BooleanField(default=False)
 
    def __str__(self):
        return self.title

tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from datetime import date, timedelta
from django.contrib import messages
import re

from .models import Task


def normalize_title(title):
        return re.sub(r'\s+', ' ', title.strip().lower())


# Create your views here.
@login_required
def index(request):
    user_id = request.user.pk
    now = date.today()
    tasks_list = Task.objects.filter(user_id=user_id)
    return render(request, "tasks/index.html", {"kind": "all", "tasks_list": tasks_list, "now": now})

@login_required
def createTask(request):
    if request.method == "POST":
        user = request.user
        raw_title = request.POST.get('title', '')
        normalized_title = normalize_title(raw_title)

        if Task.objects.filter(user_id=user, title__iexact=normalized_title).exists():
            messages.error(request, f"Task named '{normalized_title}' already exists. Title must be unique (ignoring extra spaces and casing).")
            return redirect('tasks:createTask')

        allowed_fields = ['title', 'description', 'start_at', 'due_at' ]  # only fields you can create

        if request.POST['start_at'] > request.POST['due_at']:
            messages.error(request, "Due date must be at least a day ahead of start date")
            return redirect('tasks:createTask')

        create_data = {key: request.POST[key] for key in allowed_fields if key in request.POST}

        create_data['title'] = normalized_title
        task = Task.objects.create(user_id=user, **create_data)
        messages.success(request, "Task created successfully!")
        return redirect(f'/tasks/{task.pk}')
    else:
        now = date.today()
        now_plus_1_day = date.today() + timedelta(days=1)
        context = {
            "min_1_day": now_plus_1_day,
            "now": now,
        }
        return render(request, "tasks/create.html", context)

@login_required
def singleTask(request, task_id):
    now = date.today()
    user_id = request.user.pk
    task = get_object_or_404(Task, pk=task_id, user_id=user_id)
    return render (request, "tasks/single.html", {"task": task, "now": now})
   
@login_required
def updateTask(request, task_id):
    now = date.today()
    user = request.user
    user_id = user.pk
    raw_title = request.POST.get('title', '')
    normalized_title = normalize_title(raw_title)

    task = get_object_or_404(Task, pk=task_id, user_id=user_id)
    if request.method == "POST":
        if Task.objects.filter(user_id=user, title__iexact=normalized_title).exclude(pk=task_id).exists():
            messages.error(request, f"Task named '{normalized_title}' already exists. Title must be unique (ignoring extra spaces and casing).")
            return redirect('tasks:updateTask', task_id=task.pk)

        allowed_fields = ['title', 'description', ]  # only fields to update
        if task.start_at > now:
            if request.POST['start_at'] > request.POST['due_at']:
                messages.error(request, "Due date must be at least a day ahead of start date")
                return redirect('tasks:updateTask', task_id=task.pk)
            allowed_fields.append("start_at")
        if task.due_at > now:
            allowed_fields.append("due_at")

        update_data = {key: request.POST[key] for key in allowed_fields if key in request.POST}
        update_data['title'] = normalized_title
        Task.objects.filter(pk=task_id).update(**update_data)
        messages.success(request, "Task updated successfully!")
        return redirect(f'/tasks/{task_id}')
    else:
        now_plus_1_day = date.today() + timedelta(days=1)
        context = {
            "task": task,
            "min_1_day": now_plus_1_day,
            "now": now,
        }
        return render(request, "tasks/update.html", context)

@login_required
def deleteTask(request, task_id):
    if request.method == "GET":
        raise Http404("not found")
    else:
        Task.objects.filter(pk=task_id).delete()
        messages.success(request, "Task deleted successfully!")
        return redirect('tasks:index')

@login_required
def completeTask(request, task_id):
    if request.method == "GET":
        raise Http404("not found")
    else:
        Task.objects.filter(pk=task_id).update(is_completed=True)
        messages.success(request, "Task completed successfully!")
        return redirect('tasks:singleTask', task_id)
    
@login_required
def completedTasks(request):
    now = date.today()
    user_id = request.user.pk
    completed = Task.objects.filter(user_id=user_id, is_completed=True)
    return render(request, "tasks/index.html", {"kind": "completed", "tasks_list": completed, "now": now})

@login_required
def pendingTasks(request):
    now = date.today()
    user_id = request.user.pk
    now = date.today()
    pending = Task.objects.filter(user_id=user_id, due_at__lte=now, is_completed=False)
    return render(request, "tasks/index.html", {"kind": "pending", "tasks_list": pending, "now": now})

@login_required
def runningTasks(request):
    now = date.today()
    user_id = request.user.pk
    now = date.today()
    pending = Task.objects.filter(user_id=user_id, due_at__gt=now, start_at__lte=now, is_completed=False)
    return render(request, "tasks/index.html", {"kind": "running", "tasks_list": pending, "now": now})

@login_required
def scheduledTasks(request):
    now = date.today()
    user_id = request.user.pk
    now = date.today()
    scheduled = Task.objects.filter(user_id=user_id, due_at__gt=now, start_at__gt=now, is_completed=False)
    return render(request, "tasks/index.html", {"kind": "scheduled", "tasks_list": scheduled, "now": now})

tasks/templates/tasks/create.html
{% extends "base.html" %}

{% block title %}create task{% endblock %}

{% block content %}
        <article id="create" class="singlearticle">
            <h1>create task</h1>
            <h3>fill these</h3>
            <form action="{% url 'tasks:createTask' %}" method="post">
                {% csrf_token %}
                <label for="title">title</label>
                <input type="text" name="title" id="title" required>
                <label for="description">description</label> 
                <input type="textarea" name="description" id="description" required>
                <label for="start_at">start date</label> 
                <input type="date" min="{{ now |date:'Y-m-d'}}" id="start_at" name="start_at" required>
                <label for="due_at">end date</label>
                <input type="date" min="{{ min_1_day|date:'Y-m-d'}}" id="due_at" name=due_at required>
                <button type="submit" class="submit">create</button>
            </form>
        </article>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block content %}
    <section class="alltasks">
	    <div class="flex-div"><h1>{{ kind }} tasks</h1> <a href="{% url 'tasks:createTask' %}" class="submit">New</a></div>
        {% for task in tasks_list %}
            <article class="group2">
                {% if task.is_completed %}
                    <div><i class="fa-solid fa-circle-check"></i><span>   completed</span></div>
                {% elif  now >= task.due_at %}
                    <div><i class="fa-solid fa-hourglass-half"></i><span>   pending</span></div>
                {% elif task.due_at > now and now >= task.start_at %}
                    <div><i class="fa-solid fa-arrows-rotate"></i><span>   running</span></div>
                {% else %}
                    <div><i class="fa-solid fa-bell"></i><span>   scheduled</span></div>
                {% endif %}
                <h3>{{ task.title }}</h3>
                <p>
                    {{ task.description }}
                    <span>...</span>
                </p>
                <a href="{% url 'tasks:singleTask' task.pk %}" class="submit">view task</a>
            </article>
        {% empty %}
            <div class="no-task">
                <p class="no-task-text">No Tasks Found </p>
            </div>
        {% endfor %}
    </section>
{% endblock %}

tasks/templates/tasks/single.html
{% extends "base.html" %}

{% block title %}{{ task.title }}{% endblock %}

{% block content %}
        <article class="singlearticle singletask">
            {% if task.is_completed %}
                <span>Completed on {{ task.due_at }}</span>
            {% elif  task.start_at > now %}
                <span>Starts on {{ task.start_at }}</span>
            {% elif task.due_at > now and now >= task.start_at %}
                <span>Ends on {{ task.due_at }}</span>
            {% else %}
                <span>Past due - {{ task.due_at }}</span>
            {% endif %}
            <h1>{{task.title}}</h1>
            <p>{{task.description}}</p>
            <!--<section>
                <h3>stages</h3>
                <ol>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                </ol>
            </section> -->
            <div  class="flex-div">
                {% if task.is_completed is False and now >= task.start_at %}
                    <form action="{%url 'tasks:completeTask' task.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="submit">complete</button>
                    </form>
                {% endif%}
                <form action="{%url 'tasks:deleteTask' task.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="submit">delete</button>
                </form>
                {% if task.is_completed is False %}
                    <a href="{%url 'tasks:updateTask' task.pk %}"><button  class="submit">update</button></a>
                {% endif %}
            </div>
        </article>
{% endblock %}

tasks/templates/tasks/update.html
{% extends "base.html" %}

{% block title %}Update task{% endblock %}

{% block content %}
        <article class="singlearticle" id="update">
            <h1>update - {{ task.title }}</h1>

            {% if task.is_completed %}
             <p>Completed on:     <span>{{ task.due_at }}</span></p>
            {% elif  task.start_at > now %}
                <p>Start date:     <span>{{ task.start_at }}</span></p>
            {% elif task.due_at > now and now >= task.start_at %}
             <p>End date:     <span>{{ task.due_at }}</span></p>
            {% else %}
                <p>Past due on:     <span>{{ task.due_at }}</span></p>
            {% endif %}

            <h3>fill these</h3>
            <form method="post", action="{% url 'tasks:updateTask' task.pk %}">
                {% csrf_token %}
                <label for="title">title</label> 
                <input type="text" id= "title" value="{{ task.title }}" name="title" required>
                <label for="description">description</label> 
                <input type="textarea" id="description" value="{{ task.description }}" name="description" required>
                {% if  task.start_at > now %}
                    <label for="start_at">start date</label> 
                    <input type="date" id="start_at" value="{{ task.start_at|date:'Y-m-d'}}", min="{{ now|date:'Y-m-d'}}" name="start_at" required>
                {% endif %}
                {% if task.is_completed == False %}
                    <label for="due_at">end date</label> 
                    <input type="date" id="due_at" value="{{ task.due_at|date:'Y-m-d'}}" min="{{ min_1_day|date:'Y-m-d'}}" name="due_at" required>
                {% endif %}
                <button type="submit" class="submit">update</button>
            </form>
        </article>
{% endblock %}