core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

taskly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("accounts.urls")),
    path('', include("core.urls")),
    path('tasks/', include("tasks.urls", namespace="tasks")),
    path('admin/', admin.site.urls),
]

tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.createTask, name="createTask"),
    path("<int:task_id>/", views.singleTask, name="singleTask"),
    path("<int:task_id>/update/", views.updateTask, name="updateTask"),
    path("<int:task_id>/delete/", views.deleteTask, name="deleteTask"),
    path("<int:task_id>/complete/", views.completeTask, name="completeTask"),
    path("completed/", views.completedTasks, name="completedTasks"),
    path("scheduled/", views.scheduledTasks, name="scheduledTasks"),
    path("pending/", views.pendingTasks, name="pendingTasks"),
    path("running/", views.runningTasks, name="runningTasks"),
]

templates/base.html
{% load static %}
{% include 'shared/header.html' %}

<title>{% block title %}{% endblock %} - Taskly</title>
<script src="{% static 'core/scripts/app.js' %}" type="module" crossorigin="anonymous" defer></script>

</head>
    <body>
        <header class="group2">
            <div class="logo">
		    <a href="{% url 'core:home' %}"><img src="{% static 'core/brandlogo-dark.png' %}"></a>
            </div>
            <nav>
                <div class="nav-set-1">
                    <a href="{% url 'tasks:index' %}">Tasks</a>
                    <a href="{% url 'tasks:pendingTasks' %}">Pending</a>
                    <a href="{% url 'tasks:runningTasks' %}">Running</a>
                    <a href="{% url 'tasks:scheduledTasks' %}">Scheduled</a>
                    <a href="{% url 'tasks:completedTasks' %}">Completed</a>
                </div>

                <div class="nav-set-2">
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="submit"><i class="fa-solid fa-right-from-bracket"></i><span>logout</span></button>
                        </form>
                    {% else %}
                        <a href="{% url 'login' %}" class="submit"><i class="fa-solid fa-right-to-bracket"></i><span>login</span></a>
                        <a href="{% url 'register' %}" class="submit"><i class="fa-solid fa-user-plus" style="position: relative; bottom: 3px;"></i><span>register</span></a>
                    {% endif %}
                    <div><i id="burger" class="fa-solid fa-burger"></i></div>
                </div>
            </nav>
            <div class="mobile-menu">
                <ul>
                    <li><a href="{% url 'tasks:index' %}">Tasks</a></li>
                    <li><a href="{% url 'tasks:pendingTasks' %}">Pending</a></li>
                    <li><a href="{% url 'tasks:runningTasks' %}">Running</a></li>
                    <li><a href="{% url 'tasks:scheduledTasks' %}">Scheduled</a></li>
                    <li><a href="{% url 'tasks:completedTasks' %}">Completed</a></li>
                </ul>
                
                <div>
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="submit">logout</button>
                        </form>
                    {% else %}
                        <div>
                            <a href="{% url 'login' %}" class="submit">login</a>
                            <a href="{% url 'register' %}" class="submit">register</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </header>
        {% if messages %}
            <section class="messages">
                {% for message in messages %}
                    <p class="{{ message.tags }}">{{ message }}</p>
                {% endfor %}
            </section>
        {% endif %}
        <main>
            {% block content %}{% endblock %}
        </main>
        <footer style="text-align: center;">
            <div class="flex-div"><span>Contact: charlesigboanugo033@gmail.com</span></div>
            <div class="flex-div"><span>&copy; 2025 Charles Igboanugo. All rights reserved.</span></div>
            <div class="theme-icons-box">
                <i class="fa-solid fa-sun theme-icon" data-toggle="theme-light"></i>
                <i class="fa-solid fa-moon theme-icon theme-active" data-toggle="theme-dark"></i>
            </div>
        </footer>
{% include 'shared/footer.html' %}